Adds random.choices to the random module
skulpt/skulpt pull request #1558
Opened 2024-07-27 16:21 UTC by Duncanr-glitch

Fixes #1188 

Copied the choices method from cpyhon's random module and then put it into a new random.py file that calls all the random.js functions renamed as _random.js. 

Only works in python3

2024-07-27 18:13 UTC, bnmnetp approved these changes

2024-07-30 02:10 UTC, s-cork requested changes
Thanks @Duncanr-glitch, a couple of suggestions then I think it's good to go.

2024-07-30 02:10 UTC, s-cork commented on test/unit3/test_random.py
> +    # Superclass with tests common to all generators.
Thanks for adding these
can we move TestBasicOps to the top of the file to better match the CPython test file
(makes future edits easier)
(and similar for MersenneTwister_TestBasicOps)

2024-07-30 23:23 UTC, Duncanr-glitch commented
All of that should be done I think :) Thanks for the feedback!

2024-07-31 03:09 UTC, s-cork approved these changes
LGTM - i'm happy with commenting out the python 2 syntax error for keyword only arguments.
(it doesn't break existing python 2 code)

I don't think @bnmnetp uses python 2 anymore, but @meredydd might want to just confirm that this change is ok.

2024-08-07 15:09 UTC, bnmnetp commented
python3 only

2024-10-21 16:32 UTC, meredydd commented on src/lib/random.py
> +    exec("""def choices(population, weights=None, *, cum_weights=None, k=1):
Agreed, yes.

2024-10-21 16:34 UTC, meredydd commented
(Apologies for the long delay here!)

Yes, I am happy with a change that doesn't break existing python 2 code but does accidentally expose some python 3 features in py2 mode (this is a choice we make with the stdlib all the time, and tbh even Anvil will probably want to start deprecating our py2 support soon)

2024-10-21 18:55 UTC, merged